image:
  name: boracompany/bitbucket-pipelines-baseimage:jdk11

pipelines:
  branches:
    master:
      - step:
          caches:
            - maven
          script:
            - cd src
            - mvn -Dmaven.repo.local=/local-maven-repo -DCI=true --batch-mode --settings bitbucket-settings.xml deploy

    develop:
      - step:
          caches:
            - maven
          script:
            - cd src
            - mvn -Dmaven.repo.local=/local-maven-repo -DCI=true --batch-mode --settings bitbucket-settings.xml deploy